### ISSUE TITLE
Integrate Web Sockets to make it collaborative.

### ISSUE THREAD

**Issue by s-katte** [s-katte/React-Code-Pen#1]

**Comment by ywalia01** [comment]
Hey, I'd like to work on this. Could you provide some more details?

**Comment by s-katte** [comment]
Hey @ywalia01, Thanks for having a look. 
The current version of the project works for a single user, the user can work in the prototypes just fine. 
I intend to use WebSockets in the next version where multiple users can collaborate for prototyping and making it more interactive.

**Comment by s-katte** [comment]
Solved
