### ISSUE TITLE
Alert the user before closing the tab/window.

### ISSUE THREAD

**Issue by s-katte** [s-katte/React-Code-Pen#11]
Although every change is persisted across the browser, it would be great to have an alert before closing the working tab/window.

**Comment by Rayleigh3105** [comment]
Hey, can I take on this Issue?

**Comment by s-katte** [comment]
Sure, I will assign it to you @Rayleigh3105.

**Comment by akaash11** [comment]
it need to be handled in componentDidMount with window.addEventListener and use "beforeunload",

**Comment by s-katte** [comment]
@Rayleigh3105, this project uses functional components and not class-based, so you would have to do that accordingly using hooks.

**Comment by Rayleigh3105** [comment]
You can diassociate the ticket with me, i didnt manage to get it working, sorry.

**Comment by akaash11** [comment]
Hey, I do give it a try. I have worked with Functional components and hooks @Rayleigh3105

**Comment by s-katte** [comment]
Sure, @akaash11, it is not assigned to anyone now. I will assign it to you.
Happy hacking!
