### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by gridhead** [s-katte/React-Code-Pen#13]
In the spirit of getting more contributors to the project, the above document would be appreciated.

**Comment by s-katte** [comment]
Sure @t0xic0der, Thanks for mentioning it. Will do it soon on priority.

**Comment by gridhead** [comment]
Better yet, have it assigned to folks who would be interested to do it for you.

**Comment by s-katte** [comment]
That will be fine by my side, let me know if you want to pick it up.

**Comment by bhantsi** [comment]
On it

**Comment by s-katte** [comment]
Great! I will assign it to you @bhantsi. 
Do not forget to :star: the repo 😃

**Comment by gridhead** [comment]
@bhantsi,

**Asking politely for an assignment would be appreciated.**

The maintainers of this repository spend countless hours into QAing the project and checking the stuff which can be added so the least, the contributors can do is to ask for issue assignment politely and not state that you are taking it right away.

For your reference @s-katte

**Comment by s-katte** [comment]
Rightly stated @t0xic0der.

**Comment by bhantsi** [comment]
> @bhantsi,
> 
> **Asking politely for an assignment would be appreciated.**
> 
> The maintainers of this repository spend countless hours into QAing the project and checking the stuff which can be added so the least, the contributors can do is to ask for issue assignment politely and not state that you are taking it right away.
> 
> For your reference @s-katte

Oh so sorry, thanks

**Comment by s-katte** [comment]
Hey @bhantsi, are you still working on it? To keep the flow smooth, we need to have code of conduct. If you need any help, discuss within the next 6hrs or we will have to unassign this issue.

**Comment by bhantsi** [comment]
> Hey @bhantsi, are you still working on it? To keep the flow smooth, we need to have code of conduct. If you need any help, discuss within the next 6hrs or we will have to unassign this issue.
Yes

**Comment by ShivamVerma5665** [comment]
I would like to contribute in sketchify and at this moment I think I can add the necessary details in CODE_OF_CONDUCT.md . @s-katte, will you please allow me to complete the assignment?

**Comment by s-katte** [comment]
Sure @ShivamVerma5665, assigning it to you.

Happy Hacking!

**Comment by s-katte** [comment]
merged
