### ISSUE TITLE
Facilitate Sans Serif font usage for general UI elements

### ISSUE THREAD

**Issue by gridhead** [s-katte/React-Code-Pen#14]
Add pluggable themes for folks who have a preference to Sans Serif fonts

**Comment by mcastre** [comment]
@t0xic0der i could give this a shot!

**Comment by mcastre** [comment]
@t0xic0der PR created. https://github.com/s-katte/Sketchify/pull/36

**Comment by s-katte** [comment]
There you go @mcastre, feel free to star :star: the repo :smile: 

Happy Hacking!

**Comment by mcastre** [comment]
@s-katte revised PR has been created. https://github.com/s-katte/Sketchify/pull/37
