### ISSUE TITLE
Feat: Add pull request template

### ISSUE THREAD

**Issue by s-katte** [s-katte/React-Code-Pen#19]
PR template is to be added.

**Comment by b2pacific** [comment]
I would like to work on this issue.

**Comment by b2pacific** [comment]
![Screenshot from 2020-10-16 17-58-16](https://user-images.githubusercontent.com/52305879/96258156-35364100-0fd9-11eb-868b-13906792a072.png)
The build is failing.
I think there is some problem with the workflow

**Comment by gridhead** [comment]
You were supposed to wait for an assignment before creating a PR. Any PR without an assignment is likely to be blocked - like it is now.

**Comment by b2pacific** [comment]
Is the error fixed?

**Comment by s-katte** [comment]
You will have to have some patience @b2pacific.
We are working on it.

**Comment by b2pacific** [comment]
No problem.
Sorry for that.
