### ISSUE TITLE
Update README.md according to the project.

### ISSUE THREAD

**Issue by s-katte** [s-katte/React-Code-Pen#3]

**Comment by mrcodedev** [comment]
I want assign this Issue 👍

**Comment by s-katte** [comment]
Sure thing @mrcodedev, I am assigning this issue to you.

Happy hacking!

**Comment by s-katte** [comment]
Hey @mrcodedev, It would be really appreciated to know if you are working on the issue, as this is the major issue concerning the usage of the project, I would like to have it on as early as possible :smile:

**Comment by mrcodedev** [comment]
Sorry, for various personal reasons, I can't do my homework. Sorry for the inconvenience
