### ISSUE TITLE
Add Navbar

### ISSUE THREAD

**Issue by VaibhavSaini19** [s-katte/React-Code-Pen#31]
## 🚀 Feature

Add a Navbar on the top that displays the project name and other tools / options that might be added later

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This would enhance the user experience and make it look more professional

**Comment by s-katte** [comment]
That is a good feature suggestion @VaibhavSaini19 :smiley:

**Comment by im-adithya** [comment]
Can I try this @s-katte?

**Comment by s-katte** [comment]
Sure @im-adithya, assigning it to you.

Happy Hacking!

**Comment by im-adithya** [comment]
Thank You!! Also, can you please tell me what I should include in it?

**Comment by Anurag-ak99** [comment]
hey @s-katte is the issue still open? can I contribute by adding navbar?

**Comment by s-katte** [comment]
> Thank You!! Also, can you please tell me what I should include in it?

@im-adithya We want to have a thin navigation bar area where, for this issue, only the title area is needed. There has to be an element that contains the title name and that element would become editable on focus and accordingly it will persist the changes. That title is to be added into localstorage and also to the ```Title``` tag of the HTML file.

Feel free to discuss any further assistance.

**Comment by VaibhavSaini19** [comment]
@s-katte I guess we can add the 3 download buttons in the nav as well. I would suggest Project name on the left, Document title in the middle, and the right side for tools / options (3 download buttons for now)

**Comment by s-katte** [comment]
> hey @s-katte is the issue still open? can I contribute by adding navbar?

@Anurag-ak99, This issue is assigned to @im-adithya, feel free to explore other open issues which are unassigned [here](https://github.com/s-katte/React-Code-Pen/issues) or fork the repo, use it and feel free to add any other issues and we can have a discussion on it.

**Comment by s-katte** [comment]
> @s-katte I guess we can add the 3 download buttons in the nav as well. I would suggest Project name on the left, Document title in the middle, and the right side for tools / options (3 download buttons for now)

Great suggestion! @im-adithya, we can follow the structure suggested by @VaibhavSaini19.

**Comment by im-adithya** [comment]
@s-katte, are the three buttons for downloading specific (HTML, CSS, JS) files?
I am asking so as to include appropriate icons...

**Comment by VaibhavSaini19** [comment]
@im-adithya yes. They are already present in the code (you can see them on the top right of the Iframe). You can shift them in the navbar

**Comment by s-katte** [comment]
> @s-katte, are the three buttons for downloading specific (HTML, CSS, JS) files?
> I am asking so as to include appropriate icons...

Hey, @im-adithya, @VaibhavSaini19 has answered your question I guess. If any further issues, feel free to ask.

**Comment by im-adithya** [comment]
![Screenshot (268)](https://user-images.githubusercontent.com/64399555/96692428-a6903e00-13a3-11eb-8494-eb79a04d03c3.png)
@s-katte @VaibhavSaini19 is this okay?
Any changes?
(Also, I fixed the title issue now it is working as expected)

**Comment by s-katte** [comment]
Have you shortened the height? If yes, please make it thinner.

**Comment by im-adithya** [comment]
Okay sure

**Comment by im-adithya** [comment]
![Screenshot (269)](https://user-images.githubusercontent.com/64399555/96704759-0b529500-13b2-11eb-84ce-2d95d344aa34.png)
Is this okay?
Or should I make it as that of HTML CSS JS bars?

**Comment by s-katte** [comment]
okay, that's fine.
