### ISSUE TITLE
Basic suggestions while writing code.

### ISSUE THREAD

**Issue by s-katte** [s-katte/React-Code-Pen#33]
## 🚀 Feature

Suggestions while writing code.

## Have you spent some time to check if this issue has been raised before?

Yes.

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes.

## Pitch

To give users a native editor feel, basic suggestions would do a better job to enhance their experience while developing great ideas.

**Comment by dao-phuong** [comment]
Hi, can I work on this @s-katte

**Comment by s-katte** [comment]
Sure @dao-phuong, assigning it to you.
Please star the repo if you like it :smile: 

Happy Hacking!
