### ISSUE TITLE
Custom Scroll bar

### ISSUE THREAD

**Issue by im-adithya** [s-katte/React-Code-Pen#39]
## 🚀 Feature

Custom scroll bar inside the editors

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

The present one has a default scrollbar which is light and hence doesn't go well with the dark theme of Sketchify. So I think it is better to add a custom one which suits the theme.

**Comment by s-katte** [comment]
Would you like to work on it @im-adithya ?

**Comment by im-adithya** [comment]
Yes @s-katte!

**Comment by s-katte** [comment]
There you go @im-adithya 

Happy Hacking!

**Comment by im-adithya** [comment]
![Screenshot (271)](https://user-images.githubusercontent.com/64399555/96719182-b3725900-13c6-11eb-9df3-5204bbdf98c8.png)

Is this okay @s-katte?
Any suggestions regarding width and color?

**Comment by im-adithya** [comment]
Also, while working on this, I noticed that the iframe looks plain at the start of the application.
Can we raise an issue to put up a default intro in the iframe (without its code in the editors), which disappears just as we start editing?

**Comment by s-katte** [comment]
> Is this okay @s-katte?
> Any suggestions regarding width and color?

It looks fine. We can have it.

**Comment by s-katte** [comment]
> Also, while working on this, I noticed that the iframe looks plain at the start of the application.
> Can we raise an issue to put up a default intro in the iframe (without its code in the editors), which disappears just as we start editing?

That's a great suggestion @im-adithya. We can have an issue with it. Please go ahead and make an issue.
