### ISSUE TITLE
Default Intro in iFrame

### ISSUE THREAD

**Issue by im-adithya** [s-katte/React-Code-Pen#42]
## 🚀 Feature

Default Intro in the iframe, which disappears just as we start typing.

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This improves its look as the present one is plain.
We can have there some glimpse of features of Sketchify.

**Comment by im-adithya** [comment]
@s-katte Can you assign this to me?

**Comment by s-katte** [comment]
Sure @im-adithya. There you go.

**Comment by im-adithya** [comment]
![Screenshot (272)](https://user-images.githubusercontent.com/64399555/96759867-37900500-13f6-11eb-9166-cf354e736a79.png)

Any changes @s-katte?

**Comment by VaibhavSaini19** [comment]
@im-adithya glad you are interested in this project 😄. Just a small suggestion for you. You might want to propose your solution / fix to an issue, bug or feature through a PR and discuss any further queries or changes requested in the PR itself. The issue section is mainly to discuss on what the issue/feature is, when it might occur etc and how to fix it. Discussing your proposed changes might make the thread unnecessary longer and might be painful for someone who is just looking for the solution that fixed it.
Keep hacking 😉

**Comment by im-adithya** [comment]
Got it! I'll generate a PR then.
