### ISSUE TITLE
Add "Clear Code" Option

### ISSUE THREAD

**Issue by Anushka05** [s-katte/React-Code-Pen#47]
## 🚀 Feature

There should be an option to clear the code editor.

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes
## Pitch

To enhance the user experience. This little feature would help in clearing the whole code editor.

**Comment by rrrahal** [comment]
Can I try this? (:

**Comment by s-katte** [comment]
Sure @rrrahal, assigning it to you.
Please star the repo if you like it :smile:

Happy Hacking!
