### ISSUE TITLE
Add a "Github" button on website

### ISSUE THREAD

**Issue by s-katte** [s-katte/React-Code-Pen#50]
## 🚀 Feature

Add a floating "Github" button that redirects the user to the Github repo to access the source code and explore the workflow.

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Contributing Guidelines](https://github.com/s-katte/React-Code-Pen/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

To keep users updated about the workflow of the application.

**Comment by Shreelaxmi-M** [comment]
I will do this ,can u assign it to me?

**Comment by s-katte** [comment]
Yes @shree-create, assigning it to you.

Please star the repo if you like it :smile:

**Comment by kazukilapislazuli** [comment]
Can you assign it to me?

**Comment by s-katte** [comment]
@kazukilapislazuli as you can see, this issue is already assigned. 
Have a look at other open unassigned issues [here](https://github.com/s-katte/Sketchify/issues)

Star the repo if you like it :smile:
Happy Hacking!

**Comment by talhaabbasi** [comment]
Hi, can you assign  this to me?

**Comment by s-katte** [comment]
@talhaabbasi as you can see, this issue is already assigned.
Have a look at other open unassigned issues here

Star the repo if you like it smile
Happy Hacking!

**Comment by talhaabbasi** [comment]
@s-katte Sure. I asked as the person removed the assignment :)

**Comment by s-katte** [comment]
> @s-katte Sure. I asked as the person removed the assignment :)

Sorry for the mistake and thank you for understanding.
Star the repo if you like it :smile:

**Comment by s-katte** [comment]
Hey @talhaabbasi, please update if you are still working on the issue.

**Comment by ShivamVerma5665** [comment]
Hey @s-katte, if you don't mind can you please assign me this issue. I believe I can fix this issue.

**Comment by s-katte** [comment]
there you go @ShivamVerma5665

**Comment by ShivamVerma5665** [comment]
I apologize for taking so long to complete this assignment. I will fix it asap.

**Comment by s-katte** [comment]
> I apologize for taking so long to complete this assignment. I will fix it asap.

Take your time
