### ISSUE TITLE
Add GitHub Actions and templates for issues and PRs

### ISSUE THREAD

**Issue by VaibhavSaini19** [s-katte/React-Code-Pen#7]
- Adding ESLint and Prettier GitHub Action will enhance the workflow of the repository by automatically identifying problematic patterns found in JavaScript code and formatting the code to maintain consistency.
- You can customize and standardize the information you'd like contributors to include when they open issues and pull requests in your repository with issue and pull request templates.

**Comment by s-katte** [comment]
Hey @VaibhavSaini19, would you like to pick this issue up?

**Comment by VaibhavSaini19** [comment]
@s-katte Sure

**Comment by s-katte** [comment]
There you go.
Happy Hacking :smile: !
